import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Sidebar from "./ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-zinc-950 text-white`}>
        <Sidebar />
        <div className="ml-[18vw]">{children}</div>
      </body>
    </html>
  );
}
