import './globals.css';
import Navbar from './ui/navbar';
import { lausanne } from './utils/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html className={`${lausanne.className} font-light antialiased`} lang="es">
      <Navbar />
      <body>{children}</body>
    </html>
  );
}
